ERRACT.LS      Robot Name KJLTVR111150R01RS--KU1 23-JUN-24 00:31:04  

67592434" 22-JUN-24 06:54:14 " SRVO-171 MotorSpd lim/DVC(G:1 A:3)                " " NONE                          10000000" 
67592455" 22-JUN-24 06:54:06 " SRVO-171 MotorSpd lim/DVC(G:1 A:6)                " " NONE                          10000000" 
67592487" 22-JUN-24 06:52:54 " SRVO-171 MotorSpd lim/DVC(G:1 A:3)                " " NONE                          10000000" 
67592508" 22-JUN-24 06:52:46 " SRVO-171 MotorSpd lim/DVC(G:1 A:6)                " " NONE                          10000000" 
